import {
  AGENT_STATUS_PENDING,
  AGENT_STATUS_ACTIVE,
  AGENT_STATUS_DELETED,
  AGENT_STATUS_SUSPENDED,
  AGENT_STATUS_CANCELED,
} from "@/constants/Agent";

export type AgentStatus =
  | typeof AGENT_STATUS_PENDING
  | typeof AGENT_STATUS_ACTIVE
  | typeof AGENT_STATUS_DELETED
  | typeof AGENT_STATUS_SUSPENDED
  | typeof AGENT_STATUS_CANCELED;
